version: v1

labels:
  - label: "feat"
    matcher:
      title: "^feat:.*"

  - label: "fix"
    matcher:
      title: "^fix:.*"

  - label: "chore"
    matcher:
      title: "^chore:.*"

  - label: "docs"
    matcher:
      title: "^docs:.*"

checks:
  - context: "Release Drafter"
    url: "https://github.com/fuxingloh/vue-horizontal/blob/main/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for release drafting.
    labels:
      any:
        - feat
        - fix
        - chore
        - docs
