[build]
base = "docs/"
publish = "dist/"
command = "npm run generate"
[build.environment]
GIT_LFS_ENABLED = "true"

[[headers]]
for = "/img/*"
[headers.values]
Cross-Origin-Resource-Policy = "same-origin"
