name: "SSR"

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'

  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/ssr
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: npm ci
      - run: npm run build
      - run: |
          npm run start &
          sleep 10
          npm run test
