name: CI

on:
  push:
    branches: [ main, next ]
    paths:
      - 'src/**'
      - 'dev/**'
      - '*.json'
      - '*.js'
      - '*.ts'

  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main, next ]
    paths:
      - 'src/**'
      - 'dev/**'
      - '*.json'
      - '*.js'
      - '*.ts'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: npm ci

      - run: npm run build

      - uses: andresz1/size-limit-action@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: npm ci

      - run: npm run lint
