name: edge

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main ]

jobs:
  main:
    name: End-to-end
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm ci
          start: npm run serve
          browser: edge
          spec: cypress/integration/functional/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
