name: Triage

on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]
    branches: [ main ]

jobs:
  assign:
    name: Assign
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: kentaro-m/auto-assign-action@v1.1.2
