name: Triage

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: fix, feat, docs, chore

      - uses: kentaro-m/auto-assign-action@v1.1.2
