name: Triage

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize, ready_for_review ]
    branches: [ main ]

jobs:
  main:
    name: Triage
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1
