name: Triage

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize, ready_for_review ]
    branches: [ main ]

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "fix, feat, docs, chore"
